# Generated by Django 5.0 on 2025-11-12 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacionproducto',
            name='calificacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.calificacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='comentario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.comentario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='calificacionproducto',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='categoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria'),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
