# Generated by Django 5.0 on 2025-11-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='registrocompra',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='realizado_por',
        ),
    ]
