# Generated by Django 5.0 on 2025-11-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_remove_calificacion_realizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
