# Generated by Django 5.0 on 2025-12-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_categoria_nombre_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='registro_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.registrocompra'),
        ),
    ]
