# Generated by Django 5.0 on 2025-12-08 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_solicitud_registro_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('producto', 'cliente')},
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
