"""
Django settings for ModerElectronic project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path


""" 
Librerias necesarias para el funcionamiento del proyecto

Librerias necesarias para las pruebas de rendimiento con silk

pip install django-silk
pip install locust
pip install faker

"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = BASE_DIR / 'templates'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-txs+8s2w1h@$9*uo==b68kz8x*!*^m63kd%q$s-a3ynoe9k_id'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Lista de HOSTS (IPs) que se les permite realizar peticiones al servidor de django
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.91.107.170']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # APPS DEL PROYECTO
    'Apps.Productos',
    'Apps.Usuarios',
    # App para el monitoreo de consultas SQL
    'silk',

]

MIDDLEWARE = [
    # importaciones para silk
    'silk.middleware.SilkyMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ModerElectronic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ModerElectronic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ModerElectronic',
        'USER':'root',
        'PASSWORD':''
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# STATICFILES_DIRS = [STATIC_URL]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Permite reemplazar el modelos que tiene por defecto django para la gestion de los usuarios
#             NOMBRE APP ↓    ↓ NOMBRE CLASS
AUTH_USER_MODEL = "Usuarios.Usuario"

# Redirecciones despues de iniciar y cerrar sesion
LOGIN_REDIRECT_URL = "homeGeneral"

# Redireccion despues de cerrar sesion
LOGOUT_REDIRECT_URL = "homeGeneral"

# Configuracion para el envio de correos (Consola)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# activa el analizador de código Python.
SILKY_PYTHON_PROFILER = True

# se desactivan para no bloquear la visualización del panel durante pruebas
SILKY_AUTHENTICATION = False
SILKY_AUTHORISATION = False

# máximo de peticiones guardadas.
SILKY_MAX_RECORDED_REQUESTS = 10000

# máximo de consultas SQL guardadas.
SILKY_MAX_RECORDED_QUERIES = 100000
SILKY_INTERCEPT_PERCENT = 100




