# Generated by Django 5.0 on 2025-11-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaveAcceso',
        ),
    ]
