# Generated by Django 5.0 on 2025-11-21 15:59

import Apps.Usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_delete_claveacceso'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', Apps.Usuarios.models.UsuarioManager()),
            ],
        ),
    ]
