# Generated by Django 5.0 on 2025-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_remove_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_baneado',
            field=models.BooleanField(default=False),
        ),
    ]
